#! /bin/sh
export WALLPAPERS="$HOME/Imágenes/Fondos"
export PATH="$HOME/.local/bin:$PATH"
export OUTPUT="xrandr | grep \" connected\" | awk '{print $1}' | head -n 1"

pgrep -x kwalletd6 >/dev/null || /usr/bin/kwalletd6 >/dev/null 2>&1 &

pgrep -x sxhkd > /dev/null || sxhkd &
unclutter -t 10 &
feh -z --bg-fill "$WALLPAPERS"
[ -n "$OUTPUT" ] && xrandr --output "$OUTPUT" --brightness 0.7

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

